// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yenwgvqutrhworddrfko.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InllbndndnF1dHJod29yZGRyZmtvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIzOTYyNzEsImV4cCI6MjA4Nzk3MjI3MX0.ufqO71Scvfxw1HlLND7Up_unWWrwk1vdCJKw36vFTzw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});